---
title: "**P8130 Final Report (Project 1)**"
author: 
- "Huanyu Chen (hc3451)"
- "Xiaoting Tang (xt2288)"
- "Yifei Liu (yl5508)"
- "Longyu Zhang (lz2951)"
date: "2023-12-16"
output:
  pdf_document:
    latex_engine: pdflatex

---

```{r, include=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(tidyr)
library(knitr)
library(MASS)
library(glmnet)
library(leaps)

set.seed(1)
```

# Read and Clean Data

```{r}
data =
  read_csv("./data.csv") |>
  janitor::clean_names() |>
  mutate(
    gender = factor(case_when(
      gender == "male" ~ 0,
      gender == "female" ~ 1,
      )),
    ethnic_group = factor(case_when(
      ethnic_group == "group A" ~ 0,
      ethnic_group == "group B" ~ 1,
      ethnic_group == "group C" ~ 2,
      ethnic_group == "group D" ~ 3,
      ethnic_group == "group E" ~ 4,
      )),
    parent_educ = factor(case_when(
      parent_educ == "some highschool" ~ 0,
      parent_educ == "some college" ~ 1,
      parent_educ == "associate's degree" ~ 2,
      parent_educ == "bachelor's degree" ~ 3,
      parent_educ == "master's degree" ~ 4,
      )),
    lunch_type = factor(case_when(
      lunch_type == "standard" ~ 0,
      lunch_type == "free/reduced" ~ 1,
      )),
    test_prep = factor(case_when(
      test_prep == "none" ~ 0,
      test_prep == "completed" ~ 1,
      )),
    parent_marital_status = factor(case_when(
      parent_marital_status == "married" ~ 0,
      parent_marital_status == "single" ~ 1,
      parent_marital_status == "widowed" ~ 2,
      parent_marital_status == "divorced" ~ 3,
      )),
    practice_sport = factor(case_when(
      practice_sport == "never" ~ 0,
      practice_sport == "sometimes" ~ 1,
      practice_sport == "regularly" ~ 2,
      )),
    is_first_child = factor(case_when(
      is_first_child == "no" ~ 0,
      is_first_child == "yes" ~ 1,
      )),
    transport_means = factor(case_when(
      transport_means == "school_bus" ~ 0,
      transport_means == "private" ~ 1,
      )),
    wkly_study_hours = factor(case_when(
      wkly_study_hours == "< 5" ~ 0,
      wkly_study_hours == "10-May" ~ 1,
      wkly_study_hours == "> 10" ~ 2,
      ))
    ) |>
  mutate(nr_siblings = factor(nr_siblings))

'
# Deal with NA -- Calculate the column mean (round to integer) and plug it into NA cell
column_means <- round(colMeans(data, na.rm = TRUE), digits = 0)
for (col in names(data)) {
  data[[col]][is.na(data[[col]])] <- column_means[col]
  }

head(data)
'

# Another data set for EDA
data_long <- data |>
  pivot_longer(cols = c(math_score, reading_score, writing_score),
               names_to = "test", values_to = "score")
```


# Summary

```{r}
sum_data_fct =
  data |>
  dplyr::select(1:11) |>
  skimr::skim() |>
  dplyr::select(skim_variable, n_missing, complete_rate, factor.n_unique, factor.top_counts)

colnames(sum_data_fct) = c("Variable", "Missing", "Complete Rate", "Unique", "Top Counts")

knitr::kable(x = sum_data_fct, caption = "Categorical Variables pre-analysis", digits = 1)

data =
  data |>
  drop_na()
```


```{r}
sum_data_score =
  data |>
  dplyr::select(12:14) |>
  skimr::skim() |>
  dplyr::select(skim_variable, numeric.mean, numeric.sd, numeric.p0, numeric.p25, numeric.p50, numeric.p75, numeric.p100)

colnames(sum_data_score) = c("Variable", "Mean", "SD", "Min", "Q1", "Median", "Q3", "Max")

knitr::kable(x = sum_data_score, caption = "Continuous Variables pre-analysis", digits = 1)
```

# Histograms

```{r}
data_long |>
  ggplot(aes(x = score, fill = test)) +
  geom_histogram(binwidth = 8, color = "#013571") +
  labs(
    title = "Scores Distribution by Subjects",
    x = "Score",
    y = "Count"
    ) +
  scale_fill_manual(values = c("#2E4E7D", "#405165", "#67A9CB")) +
  facet_grid(~ test) +
  theme_bw() +
  theme(legend.position = "bottom") +
  theme(plot.title = element_text(size = 15, face = "bold", hjust = 0.5))
```

# Boxplots

```{r}
data_long |>
  ggplot(aes(x = test, y = score, fill = test)) +
  geom_boxplot() +
  labs(
    title = "Scores Boxplot by Subjects",
    x = "Test",
    y = "Score"
    ) +
  facet_wrap(~ test, scales = "free") +
  scale_fill_manual(values = c("#2E4E7D", "#405165", "#67A9CB")) +
  theme_bw() +
  theme(legend.position = "bottom") +
  theme(plot.title = element_text(size = 15, face = "bold", hjust = 0.5))
```

# Diagnostics

```{r}
# Math
model_math_full = lm(math_score ~ . - reading_score - writing_score, data = data)
model_math_full |> summary()
par(mfrow = c(2,2))
plot(model_math_full)

# Reading
model_reading_full = lm(reading_score ~ . - math_score - writing_score, data = data)
model_reading_full |> summary()
par(mfrow = c(2,2))
plot(model_reading_full)

# Writing
model_writing_full = lm(writing_score ~ . - reading_score - math_score, data = data)
model_writing_full |> summary()
par(mfrow = c(2,2))
plot(model_writing_full)
```

# criterion-based Procedures

```{r}
math_c = regsubsets(math_score ~ . - reading_score - writing_score, data = data)
res_math =
  math_c |>
  summary()

reading_c = regsubsets(reading_score ~ . - math_score - writing_score, data = data)
res_reading =
  math_c |>
  summary()

writing_c = regsubsets(writing_score ~ . - math_score - reading_score, data = data)
res_writing =
  math_c |>
  summary()

par(mfrow = c(1, 3), mar = c(8, 4, 4, 1))
plot(1:8, res_math$bic, xlab = "# of parameters", ylab = "BIC")
plot(1:8, res_reading$bic, xlab = "# of parameters", ylab = "BIC")
plot(1:8, res_writing$bic, xlab = "# of parameters", ylab = "BIC")

res_math$outmat[5,]
res_reading$outmat[5,]
res_writing$outmat[5,]
```

# Transformation

```{r}
par(mfrow = c(1, 3), mar = c(8, 4, 4, 1))
boxcox(model_math_full)
boxcox(model_reading_full)
boxcox(model_writing_full)
```

# Outlier and influence points

```{r}
par(mfrow = c(1, 3), mar = c(8, 4, 4, 1))
plot(model_math_full, which = 4)
plot(model_reading_full, which = 4)
plot(model_writing_full, which = 4)
```

# Multicollinearity

```{r}
# check VIF
vif_math =
  performance::check_collinearity(model_math_full) |>
  as_tibble() |>
  mutate(VIF_CI = str_c("[", round(VIF_CI_low, 1), ", ", round(VIF_CI_high, 1), "]")) |>
  dplyr::select(Term, VIF, VIF_CI, Tolerance)
knitr::kable(x = vif_math, caption = "VIF for Math Score", digits = 1)

vif_reading =
  performance::check_collinearity(model_reading_full) |>
  as_tibble() |>
  mutate(VIF_CI = str_c("[", round(VIF_CI_low, 1), ", ", round(VIF_CI_high, 1), "]")) |>
  dplyr::select(Term, VIF, VIF_CI, Tolerance)
knitr::kable(x = vif_reading, caption = "VIF for Reading Score", digits = 1)

vif_writing =
  performance::check_collinearity(model_writing_full) |>
  as_tibble() |>
  mutate(VIF_CI = str_c("[", round(VIF_CI_low, 1), ", ", round(VIF_CI_high, 1), "]")) |>
  dplyr::select(Term, VIF, VIF_CI, Tolerance)
knitr::kable(x = vif_writing, caption = "VIF for Reading Score", digits = 1)
```


# Model Selections

## Stepwise Regressions

```{r}
# math
math_sr = step(model_math_full, direction = 'both', trace = FALSE)

res_math_sr = math_sr |> 
  summary()
res_math_sr

tb_math_sr = res_math_sr |>
  broom::tidy() |>
  filter(term != "(Intercept)") |> 
  dplyr::select(term, estimate, p.value)
colnames(tb_math_sr) = c("Term", "Estimate", "P Value")
knitr::kable(x = tb_math_sr, caption = "Math Scores Models by Stepwise Regression", digits = 1)

# reading
rea_sr = step(model_reading_full, direction = 'both')

res_rea_sr = rea_sr |> 
  summary()
res_rea_sr

tb_rea_sr = res_rea_sr |>
  broom::tidy() |>
  filter(term != "(Intercept)") |> 
  dplyr::select(term, estimate, p.value)
colnames(tb_rea_sr) = c("Term", "Estimate", "P Value")
knitr::kable(x = tb_rea_sr, caption = "Reading Scores Models by Stepwise Regression", digits = 1)

# writing
wri_sr = step(model_writing_full, direction = 'both')

res_wri_sr = wri_sr |> 
  summary()
res_wri_sr

tb_wri_sr = res_wri_sr |>
  broom::tidy() |>
  filter(term != "(Intercept)") |> 
  dplyr::select(term, estimate, p.value)
colnames(tb_wri_sr) = c("Term", "Estimate", "P Value")
knitr::kable(x = tb_wri_sr, caption = "Writing Scores Models by Stepwise Regression", digits = 1)
```

## Lasso Models

```{r}
lambda_seq = 10 ^ seq(-2, 2, by = .1)

#math
cv_object_math = 
  cv.glmnet(as.matrix(data[1:11]), data$math_score,
                         lambda = lambda_seq,
                         nfolds = 5)

opt_lambda_math = cv_object_math$lambda.min

#variables contraction
glmnet(as.matrix(data[1:11]), data$math_score, lambda = lambda_seq) |>
  broom::tidy() |>
  dplyr::select(term, lambda, estimate) |> 
  complete(term, lambda, fill = list(estimate = 0) ) |> 
  filter(term != "(Intercept)") |> 
  ggplot(aes(x = log(lambda, 10), y = estimate, group = term, color = term)) + 
  geom_path(size = 0.8) + 
  geom_vline(xintercept = log(opt_lambda_math, 10), color = "red", linetype = "dashed", size = 1) +
  theme_bw() +
  theme(legend.position = "bottom")

tb_la_math = tibble(
  lambda = cv_object_math$lambda,
  mean_cv_error = cv_object_math$cvm) |>
  filter(lambda < 1)

#choosing optimal lambda
tb_la_math |>
  ggplot(aes(x = lambda, y = mean_cv_error)) +
  geom_point() +
  theme_bw()

#math result
model_math_lasso = glmnet(as.matrix(data[1:11]), data$math_score, lambda = opt_lambda_math, alpha = 1)
coef(model_math_lasso)
model_math_lasso$dev.ratio
```


```{r}
#reading
cv_object_reading = 
  cv.glmnet(as.matrix(data[1:11]), data$reading_score,
                         lambda = lambda_seq,
                         nfolds = 5)

opt_lambda_reading = cv_object_reading$lambda.min

#variables contraction
glmnet(as.matrix(data[1:11]), data$reading_score, lambda = lambda_seq) |>
  broom::tidy() |>
  dplyr::select(term, lambda, estimate) |> 
  complete(term, lambda, fill = list(estimate = 0) ) |> 
  filter(term != "(Intercept)") |> 
  ggplot(aes(x = log(lambda, 10), y = estimate, group = term, color = term)) + 
  geom_path(size = 0.8) + 
  geom_vline(xintercept = log(opt_lambda_reading, 10), color = "red", linetype = "dashed", size = 1) +
  theme_bw() +
  theme(legend.position = "bottom")

tb_la_reading = tibble(
  lambda = cv_object_reading$lambda,
  mean_cv_error = cv_object_reading$cvm) |>
  filter(lambda < 1)

#choosing optimal lambda
tb_la_reading |>
  ggplot(aes(x = lambda, y = mean_cv_error)) +
  geom_point() +
  theme_bw()

#reading result
model_reading_lasso = glmnet(as.matrix(data[1:11]), data$reading_score, lambda = opt_lambda_math, alpha = 1)
coef(model_reading_lasso)
model_reading_lasso$dev.ratio
```


```{r}
#writing
cv_object_writing = 
  cv.glmnet(as.matrix(data[1:11]), data$writing_score,
                         lambda = lambda_seq,
                         nfolds = 5)

opt_lambda_writing = cv_object_writing$lambda.min

#variables contraction
glmnet(as.matrix(data[1:11]), data$writing_score, lambda = lambda_seq) |>
  broom::tidy() |>
  dplyr::select(term, lambda, estimate) |> 
  complete(term, lambda, fill = list(estimate = 0) ) |> 
  filter(term != "(Intercept)") |> 
  ggplot(aes(x = log(lambda, 10), y = estimate, group = term, color = term)) + 
  geom_path(size = 0.8) + 
  geom_vline(xintercept = log(opt_lambda_writing, 10), color = "red", linetype = "dashed", size = 1) +
  theme_bw() +
  theme(legend.position = "bottom")

tb_la_writing = tibble(
  lambda = cv_object_writing$lambda,
  mean_cv_error = cv_object_writing$cvm) |>
  filter(lambda < 1)

#choosing optimal lambda
tb_la_writing |>
  ggplot(aes(x = lambda, y = mean_cv_error)) +
  geom_point() +
  theme_bw()

#writing result
model_writing_lasso = glmnet(as.matrix(data[1:11]), data$writing_score, lambda = opt_lambda_writing, alpha = 1)
coef(model_writing_lasso)
model_writing_lasso$dev.ratio
```

## adding one score variable

```{r}
#correlation plot for scores
corrplot::corrplot(cor(data[12:14]), type = "upper")
```


```{r}
# Math
math_reading = lm(math_score ~ . - writing_score, data = data) |>
  step(direction = "both")
math_reading |> summary()

math_writing = lm(math_score ~ . - reading_score, data = data) |>
  step(direction = "both")
math_writing |> summary()

# Reading
reading_math = lm(reading_score ~ . - writing_score, data = data) |>
  step(direction = "both")
reading_math |> summary()

reading_writing = lm(reading_score ~ . - math_score, data = data) |>
  step(direction = "both")
reading_writing |> summary()

# Writing
writing_math = lm(writing_score ~ . - reading_score, data = data) |>
  step(direction = "both")
writing_math |> summary()

writing_reading = lm(writing_score ~ . - math_score, data = data) |>
  step(direction = "both")
writing_reading |> summary()
```


```{r}
# check VIF
vif_math_reading =
  performance::check_collinearity(math_reading) |>
  as_tibble() |>
  mutate(VIF_CI = str_c("[", round(VIF_CI_low, 1), ", ", round(VIF_CI_high, 1), "]")) |>
  dplyr::select(Term, VIF, VIF_CI, Tolerance)
knitr::kable(x = vif_math_reading, caption = "VIF for Math Score", digits = 1)

vif_math_writing =
  performance::check_collinearity(math_writing) |>
  as_tibble() |>
  mutate(VIF_CI = str_c("[", round(VIF_CI_low, 1), ", ", round(VIF_CI_high, 1), "]")) |>
  dplyr::select(Term, VIF, VIF_CI, Tolerance)
knitr::kable(x = vif_math_writing, caption = "VIF for Math Score", digits = 1)

vif_reading_math =
  performance::check_collinearity(reading_math) |>
  as_tibble() |>
  mutate(VIF_CI = str_c("[", round(VIF_CI_low, 1), ", ", round(VIF_CI_high, 1), "]")) |>
  dplyr::select(Term, VIF, VIF_CI, Tolerance)
knitr::kable(x = vif_reading_math, caption = "VIF for Reading Score", digits = 1)

vif_reading_writing =
  performance::check_collinearity(reading_writing) |>
  as_tibble() |>
  mutate(VIF_CI = str_c("[", round(VIF_CI_low, 1), ", ", round(VIF_CI_high, 1), "]")) |>
  dplyr::select(Term, VIF, VIF_CI, Tolerance)
knitr::kable(x = vif_reading_writing, caption = "VIF for Reading Score", digits = 1)

vif_writing_math =
  performance::check_collinearity(writing_math) |>
  as_tibble() |>
  mutate(VIF_CI = str_c("[", round(VIF_CI_low, 1), ", ", round(VIF_CI_high, 1), "]")) |>
  dplyr::select(Term, VIF, VIF_CI, Tolerance)
knitr::kable(x = vif_writing_math, caption = "VIF for Reading Score", digits = 1)

vif_writing_reading =
  performance::check_collinearity(writing_reading) |>
  as_tibble() |>
  mutate(VIF_CI = str_c("[", round(VIF_CI_low, 1), ", ", round(VIF_CI_high, 1), "]")) |>
  dplyr::select(Term, VIF, VIF_CI, Tolerance)
knitr::kable(x = vif_writing_reading, caption = "VIF for Reading Score", digits = 1)
```


